### ISSUE TITLE
Flatten the file structure

### ISSUE THREAD

**Issue by xu-chris** [TimOetting/kirby-list-field#1]
First: thanks for your awesome idea and very cool and simple solution!

I have a suggestion regarding your file structure: because of the structure I can't add your awesome plugin as a submodule. please bring every file in the `list`-folder into the root of your Github project. Look to a similar discussion at an other Kirby plugin: https://github.com/distantnative/footnotes/issues/5

**Comment by JonasDoebertin** [comment]
👍

**Comment by tweh** [comment]
Hi @TimOetting any news on this (rather small) issue? :-)

**Comment by TimOetting** [comment]
Done. Sorry for not fixing this quicker.
