### ISSUE TITLE
->limit() not working

### ISSUE THREAD

**Issue by mxub** [TimOetting/kirby-list-field#4]
it seems that I can't limit the entrynumber with `$list->limit(2)->yaml()` I always get the whole list

**Comment by TimOetting** [comment]
Hey maxxst,

try `$list->toStructure()->limit(2)`

`$list` is a simple yaml string that does not come with a `limit()` function. `yaml()` would convert is to a simple array which won't have a `limit()` function too. Therefore you have to call `toStructure()` to convert it to the more versatile kirby collection.
