### ISSUE TITLE
German Umlaute

### ISSUE THREAD

**Issue by ghost** [TimOetting/kirby-list-field#5]
![kapture 2017-03-01 at 14 06 15](https://cloud.githubusercontent.com/assets/18130498/23461032/6298bf62-fe88-11e6-81af-8c14a7f2bf3f.gif)

Everytime i save something in the panel, the list item gets added another umlaute encoding and therefore makes them invalid.

**Comment by fooness** [comment]
Hey @novacanye, I experienced some similar problems. Please try changing line 32 in fields/list/list.php from `$input->val(html($value, false));` to `$input->val($value, false);` …

That fixed the problem in my case. Maybe then other problems appear?

Is it possible for you to use kirby’s markup in those lists, like e.g. `(link: http://creativecommons.org/licenses/by-nc-nd/4.0 class: without-underline text: CC BY-NC-ND 4.0 popup: yes)`?

I’m just trying to find out what’s the problem with this markup not being rendered …

**Comment by tobiasfabian** [comment]
> Is it possible for you to use kirby’s markup in those lists, like e.g. (link: http://creativecommons.org/licenses/by-nc-nd/4.0 class: without-underline text: CC BY-NC-ND 4.0 popup: yes)?

You can use [`kirbytext()`](https://getkirby.com/docs/cheatsheet/helpers/kirbytext) to render the markup. 

```php
<?php foreach($page->fruits()->yaml() as $item) : ?>
  <li><?= kirbytext($item) ?></li>
<?php endforeach ?>
```

If you want to avoid the surrounding `p` tags you can use the **[kirbytextRaw](https://github.com/jbeyerstedt/kirby-plugin-kirbytextRaw)** plugin from @jbeyerstedt
