### ISSUE TITLE
Field inside script

### ISSUE THREAD

**Issue by jenstornell** [TimOetting/kirby-list-field#8]
In the Google Developer Tools it looks like the input field appear inside a script tag.

```php
<script class="list-item-template" type="text/x-handlebars-template">
    <div class="list-item">
      <input class="input" type="list" name="fruits[]" autocomplete="on" id="form-field-fruits">      <div class="field-icon sortable-handle"><i class="icon fa fa-arrows"></i></div>
    </div>

</script>
```

**Comment by TimOetting** [comment]
@jenstornell this is a template that is taken as a blueprint when a new row is added. Its only purpose is to be used as such a template. It is not rendered directly. The only issue I see here is that is has the type "text/x-handlebars-template" without being a handlebar template. It could be changed to the type "text/template"

**Comment by jenstornell** [comment]
Ahh, I see. Then I'll guess it's fine. I just never seen a script template before, divs inside a script tag.

Anyway, the next version of my [Engineer field](https://github.com/jenstornell/field-engineer) will support your list field. After a few adjustments in my js (on my localhost), it works great.
