### ISSUE TITLE
Encoding problem for strange characters

### ISSUE THREAD

**Issue by jenstornell** [TimOetting/kirby-list-field#9]
![list](https://user-images.githubusercontent.com/927011/27796504-82170860-600a-11e7-9d05-e68b2124895e.gif)

It works fine with a normal text field but not with the list field.

**Comment by TimOetting** [comment]
Hey @jenstornell , this has just been fixed with this pull request https://github.com/TimOetting/kirby-list-field/pull/7

**Comment by jenstornell** [comment]
I can confirm that it works, even in Engineer. =)
